# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'photo_tutorial' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for photo_tutorial
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

  target 'photo_tutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
